### ISSUE TITLE
App crashing while scanning QR, Fatal exception, java.lang.IllegalArgumentException: Unsupported value: '[Ljava.lang.String;@a2b19a3' of type 'class [Ljava.lang.String;'

### ISSUE THREAD

**Issue by raymond-manithara** [juliansteenbakker/mobile_scanner#108]
While trying to scan a QR code the app got crashed. 

Both scan and image upload have the issue.

I wasn't able to handle the crash using exception handling in flutter.

This is the code used.

```
try {

      final ImagePicker _picker = ImagePicker();

      final XFile? image = await _picker.pickImage(source: ImageSource.gallery);

      if (image != null) {

        log("image_path: ${image.path}");

        bool result = await controller.analyzeImage(image.path);

        if (result) {

        } else {

         log("Failed to load");

        }
      } else {

        throw Exception("Image not selected");

      }
    } catch (e) {
      log("ERROR: $e");
    }
```

Stack-trace from flutter run --verbose

```
[+12154 ms] I/sample.qrscanne( 1920): Background concurrent copying GC freed 123617(4222KB) AllocSpace objects, 4(80KB) LOS objects, 49% free, 4080KB/8161KB, paused
159us total 171.164ms
[+9245 ms] D/AndroidRuntime( 1920): Shutting down VM
[  +11 ms] E/AndroidRuntime( 1920): FATAL EXCEPTION: main
[        ] E/AndroidRuntime( 1920): Process: com.sample.qrscanner, PID: 1920
[        ] E/AndroidRuntime( 1920): java.lang.IllegalArgumentException: Unsupported value: '[Ljava.lang.String;@a2b19a3' of type 'class [Ljava.lang.String;'
[        ] E/AndroidRuntime( 1920):     at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:292)
[        ] E/AndroidRuntime( 1920):     at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:280)
[        ] E/AndroidRuntime( 1920):     at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:272)
[        ] E/AndroidRuntime( 1920):     at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:280)
[        ] E/AndroidRuntime( 1920):     at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:280)
[        ] E/AndroidRuntime( 1920):     at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:280)
[        ] E/AndroidRuntime( 1920):     at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:59)
[        ] E/AndroidRuntime( 1920):     at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:251)
[        ] E/AndroidRuntime( 1920):     at dev.steenbakker.mobile_scanner.MobileScanner.analyzer$lambda-4$lambda-1(MobileScanner.kt:108)
[        ] E/AndroidRuntime( 1920):     at dev.steenbakker.mobile_scanner.MobileScanner.lambda$W_K0wEAtbLY7GWki1OWglBLUf6o(Unknown Source:0)
[        ] E/AndroidRuntime( 1920):     at dev.steenbakker.mobile_scanner.-$$Lambda$MobileScanner$W_K0wEAtbLY7GWki1OWglBLUf6o.onSuccess(Unknown Source:4)
[        ] E/AndroidRuntime( 1920):     at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
[        ] E/AndroidRuntime( 1920):     at android.os.Handler.handleCallback(Handler.java:938)
[        ] E/AndroidRuntime( 1920):     at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/AndroidRuntime( 1920):     at android.os.Looper.loop(Looper.java:223)
[        ] E/AndroidRuntime( 1920):     at android.app.ActivityThread.main(ActivityThread.java:7700)
[        ] E/AndroidRuntime( 1920):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 1920):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
[        ] E/AndroidRuntime( 1920):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```
QR code used

![image](https://user-images.githubusercontent.com/83985003/164463411-6ec7cc8c-0873-40cf-9c2e-c598a94dc432.png)

Device which issue shown

Nokia 2.3
Android version 11
Model & hardware : TA-1209
Build number : 00WW_3_310_SP02

**Comment by juliansteenbakker** [comment]
This seems to be working fine with version 3.0.0-beta.4
