### ISSUE TITLE
Not requesting permission to use camera on web

### ISSUE THREAD

**Issue by mklepaczko** [juliansteenbakker/mobile_scanner#1082]
Hello,

I'm using v4 in a project and it works fine. I now implemented the latest version in another project and when opening the simple scanning widget from your example on web / ios is does not ask for permission, although it asks it on web /mac os.

IOS 17.4.1
Same for Chrome and Safari

**Comment by navaronbracke** [comment]
Could you provide the browser logs for iOS Safari when this occurs?

We have a similar issue, but for in-app browsers on iOS: https://github.com/juliansteenbakker/mobile_scanner/issues/950#issuecomment-2136595869

**Comment by mklepaczko** [comment]
I see now it happens also on desktop Chrome Mac OS:

Wersja 124.0.6367.202 (Oficjalna wersja) (arm64)

MissingPluginException(No implementation found for method listen on channel dev.steenbakker.mobile_scanner/scanner/event)
main.dart.js:40018     at Object.h (https://pukpuk-app.web.app/main.dart.js:5152:19)
main.dart.js:40018     at https://pukpuk-app.web.app/main.dart.js:96936:15
main.dart.js:40018     at blm.a (https://pukpuk-app.web.app/main.dart.js:6532:63)
main.dart.js:40018     at blm.$2 (https://pukpuk-app.web.app/main.dart.js:54454:14)
main.dart.js:40018     at bk1.$1 (https://pukpuk-app.web.app/main.dart.js:54448:21)
main.dart.js:40018     at bgB.aHY (https://pukpuk-app.web.app/main.dart.js:55643:34)
main.dart.js:40018     at bgB.AJ (https://pukpuk-app.web.app/main.dart.js:55646:13)
main.dart.js:40018     at bd3.$0 (https://pukpuk-app.web.app/main.dart.js:54924:11)
main.dart.js:40018     at Object.DM (https://pukpuk-app.web.app/main.dart.js:6677:40)
main.dart.js:40018     at al.oK (https://pukpuk-app.web.app/main.dart.js:54850:3)
main.dart.js:7728 Uncaught MissingPluginException(No implementation found for method state on channel dev.steenbakker.mobile_scanner/scanner/method)
    at Object.h (https://pukpuk-app.web.app/main.dart.js:5152:19)
    at https://pukpuk-app.web.app/main.dart.js:96936:15
    at blm.a (https://pukpuk-app.web.app/main.dart.js:6532:63)
    at blm.$2 (https://pukpuk-app.web.app/main.dart.js:54454:14)
    at bk1.$1 (https://pukpuk-app.web.app/main.dart.js:54448:21)
    at bgB.aHY (https://pukpuk-app.web.app/main.dart.js:55643:34)
    at bgB.AJ (https://pukpuk-app.web.app/main.dart.js:55646:13)
    at bd3.$0 (https://pukpuk-app.web.app/main.dart.js:54924:11)
    at Object.DM (https://pukpuk-app.web.app/main.dart.js:6677:40)
    at al.oK (https://pukpuk-app.web.app/main.dart.js:54850:3)
main.dart.js:5152 Uncaught MissingPluginException(No implementation found for method state on channel dev.steenbakker.mobile_scanner/scanner/method)
    at Object.h (https://pukpuk-app.web.app/main.dart.js:5152:19)
    at https://pukpuk-app.web.app/main.dart.js:96936:15
    at blm.a (https://pukpuk-app.web.app/main.dart.js:6532:63)
    at blm.$2 (https://pukpuk-app.web.app/main.dart.js:54454:14)
    at bk1.$1 (https://pukpuk-app.web.app/main.dart.js:54448:21)
    at bgB.aHY (https://pukpuk-app.web.app/main.dart.js:55643:34)
    at bgB.AJ (https://pukpuk-app.web.app/main.dart.js:55646:13)
    at bd3.$0 (https://pukpuk-app.web.app/main.dart.js:54924:11)
    at Object.DM (https://pukpuk-app.web.app/main.dart.js:6677:40)

**Comment by navaronbracke** [comment]
What version of `mobile_scanner` are you using? Version 5.0.0 does not use `MethodChannel/EventChannel` on the web, but instead uses `dart:js_interop` to call out to Javascript API's for its implementation.

Is your pub cache up to date? Perhaps you need to do `flutter clean` followed by `flutter pub get`.

See also https://github.com/juliansteenbakker/mobile_scanner/blob/master/lib/src/web/mobile_scanner_web.dart

**Comment by mklepaczko** [comment]
using 5.1.1, flutter clean solved it. Sorry about that and thanks for your help!
