### ISSUE TITLE
Request connection error

### ISSUE THREAD

**Issue by yerzhant** [juliansteenbakker/mobile_scanner#1108]
With this code:
```
    private val endpointDiscoveryCallback = object : EndpointDiscoveryCallback() {
        override fun onEndpointFound(
            endpoint: String,
            discoveredEndpointInfo: DiscoveredEndpointInfo
        ) {
            remoteEndpoint = endpoint
            client.requestConnection(
                "Receiver",
                endpoint,
                discovererConnectionCallback
            )
                .addOnSuccessListener { client.stopDiscovery() }
                .addOnFailureListener { Log.e(logTag, "Failed to request a connection", it) }
        }

        override fun onEndpointLost(endpoint: String) {
            Log.e(logTag, "Endpoint $endpoint lost")
        }
    }

    override fun discover() {
        val options = DiscoveryOptions.Builder().setStrategy(P2P_POINT_TO_POINT).build()
        client.startDiscovery(serviceId, endpointDiscoveryCallback, options)
            .addOnFailureListener { Log.e(logTag, "Discovery failed", it) }
    }
```
First run is fine but the second and further ones return this error:
```
E/NearByService(31054): Failed to request a connection
E/NearByService(31054): com.google.android.gms.common.api.ApiException: 13: ERROR
E/NearByService(31054): 	at com.google.android.gms.internal.nearby.zzdo.setFailedResult(com.google.android.gms:play-services-nearby@@19.2.0:1)
E/NearByService(31054): 	at com.google.android.gms.internal.nearby.zzce.zzb(com.google.android.gms:play-services-nearby@@19.2.0:4)
E/NearByService(31054): 	at com.google.android.gms.internal.nearby.zzfr.zza(com.google.android.gms:play-services-nearby@@19.2.0:3)
E/NearByService(31054): 	at com.google.android.gms.internal.nearby.zzb.onTransact(com.google.android.gms:play-services-nearby@@19.2.0:3)
E/NearByService(31054): 	at android.os.Binder.execTransactInternal(Binder.java:1380)
E/NearByService(31054): 	at android.os.Binder.execTransact(Binder.java:1311)
```

**Comment by navaronbracke** [comment]
This has nothing to do with mobile_scanner?

**Comment by yerzhant** [comment]
Sorry, it meant to be opened in google/nearby.
https://github.com/google/nearby/issues/2666
