### ISSUE TITLE
Camera not found on Android 11

### ISSUE THREAD

**Issue by Maryusz** [juliansteenbakker/mobile_scanner#1109]
Hello, 
I have the following issue only on some Android 11 phones. 

```shell
D/CameraValidator( 2192): Verifying camera lens facing on A13, lensFacingInteger: null
E/CameraValidator( 2192): Camera LensFacing verification failed, existing cameras: [Camera@131caf1[id=0], Camera@8201aae[id=1], Camera@9f231c8[id=3], Camera@cf433e3[id=4]]
W/CameraX ( 2192): Retry init. Start time 1137333660 current time 1137333810
W/CameraX ( 2192): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 2192): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:97)
W/CameraX ( 2192): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:334)
W/CameraX ( 2192): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda3.run(Unknown Source:10)
W/CameraX ( 2192): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 2192): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 2192): 	at java.lang.Thread.run(Thread.java:923)
W/CameraX ( 2192): Caused by: java.lang.IllegalArgumentException: The given lens facing integer: 255 can not be recognized.
W/CameraX ( 2192): 	at androidx.camera.camera2.internal.LensFacingUtil.getCameraSelectorLensFacing(LensFacingUtil.java:56)
W/CameraX ( 2192): 	at androidx.camera.camera2.internal.Camera2CameraInfoImpl.getLensFacing(Camera2CameraInfoImpl.java:198)
W/CameraX ( 2192): 	at androidx.camera.core.impl.LensFacingCameraFilter.filter(LensFacingCameraFilter.java:48)
W/CameraX ( 2192): 	at androidx.camera.core.CameraSelector.filter(CameraSelector.java:128)
W/CameraX ( 2192): 	at androidx.camera.core.CameraSelector.filter(CameraSelector.java:153)
W/CameraX ( 2192): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:90)
W/CameraX ( 2192): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:83)
W/CameraX ( 2192): 	... 5 more
D/CameraRepository( 2192): Added camera: 0
I/Camera2CameraInfo( 2192): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository( 2192): Added camera: 1
I/Camera2CameraInfo( 2192): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository( 2192): Added camera: 3
I/Camera2CameraInfo( 2192): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository( 2192): Added camera: 4
I/Camera2CameraInfo( 2192): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
```

This doesn't permit to scan any code.  
Is there any solution to this?

**Comment by navaronbracke** [comment]
What type of camera is camera id 2 ? Because that one seems to be missing?

Is this a USB camera?

**Comment by Maryusz** [comment]
Nope, is an integrated camera in a phone (Umidigi phone).
There's 2 cameras in the back of the phone and one in front of it.

We have 5 of them and all have the same issue. 

I had a similar issue on an old ZTE phone but I didn't have the possibility to debug it.

**Comment by juliansteenbakker** [comment]
I'm closing this as there is no activity, and newer versions of this plug are already released. If this still happens with the latest version let me know by commenting.

**Comment by Ignacio1224** [comment]
I am facing the same issue, Android 11

However the cammera is working and passed some time, the controller starts and works well

```
late final MobileScannerController _scannerController;

  @override
  void initState() {
    super.initState();
    _initScannerController();
  }

  @override
  void dispose() {
    _scannerController.dispose();
    super.dispose();
  }

  void _initScannerController() async {
    _scannerController = MobileScannerController(
      detectionSpeed: DetectionSpeed.noDuplicates,
      formats: const [BarcodeFormat.code128],
      returnImage: false,
      torchEnabled: true,
      invertImage: false,
      autoZoom: false,
      facing: CameraFacing.back,
      autoStart: false,
    );

    if (!_scannerController.value.isStarting) {
      await _scannerController.start();
    }
  }
```

```
I/Camera2CameraInfo( 4994): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
W/CameraValidator( 4994): Camera LENS_FACING_FRONT verification failed
W/CameraValidator( 4994): java.lang.IllegalArgumentException: No available camera can be found
W/CameraValidator( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraValidator( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraValidator( 4994): 	at java.lang.Thread.run(Thread.java:923)
E/CameraValidator( 4994): Camera LensFacing verification failed, existing cameras: [Camera@c195bd0[id=0]]
W/CameraX ( 4994): Retry init. Start time 22170954 current time 22171536
W/CameraX ( 4994): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:142)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4994): 	at java.lang.Thread.run(Thread.java:923)
W/CameraX ( 4994): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraX ( 4994): 	... 5 more
I/Camera2CameraInfo( 4994): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
W/CameraValidator( 4994): Camera LENS_FACING_FRONT verification failed
W/CameraValidator( 4994): java.lang.IllegalArgumentException: No available camera can be found
W/CameraValidator( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraValidator( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraValidator( 4994): 	at java.lang.Thread.run(Thread.java:923)
E/CameraValidator( 4994): Camera LensFacing verification failed, existing cameras: [Camera@9190fe7[id=0]]
W/CameraX ( 4994): Retry init. Start time 22170954 current time 22172104
W/CameraX ( 4994): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:142)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4994): 	at java.lang.Thread.run(Thread.java:923)
W/CameraX ( 4994): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraX ( 4994): 	... 5 more
I/Camera2CameraInfo( 4994): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
W/CameraValidator( 4994): Camera LENS_FACING_FRONT verification failed
W/CameraValidator( 4994): java.lang.IllegalArgumentException: No available camera can be found
W/CameraValidator( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraValidator( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraValidator( 4994): 	at java.lang.Thread.run(Thread.java:923)
E/CameraValidator( 4994): Camera LensFacing verification failed, existing cameras: [Camera@95ecbf5[id=0]]
W/CameraX ( 4994): Retry init. Start time 22170954 current time 22172722
W/CameraX ( 4994): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:142)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4994): 	at java.lang.Thread.run(Thread.java:923)
W/CameraX ( 4994): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraX ( 4994): 	... 5 more
I/Camera2CameraInfo( 4994): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
W/CameraValidator( 4994): Camera LENS_FACING_FRONT verification failed
W/CameraValidator( 4994): java.lang.IllegalArgumentException: No available camera can be found
W/CameraValidator( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraValidator( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraValidator( 4994): 	at java.lang.Thread.run(Thread.java:923)
E/CameraValidator( 4994): Camera LensFacing verification failed, existing cameras: [Camera@38184ad[id=0]]
W/CameraX ( 4994): Retry init. Start time 22170954 current time 22173294
W/CameraX ( 4994): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:142)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4994): 	at java.lang.Thread.run(Thread.java:923)
W/CameraX ( 4994): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraX ( 4994): 	... 5 more
I/Camera2CameraInfo( 4994): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
W/CameraValidator( 4994): Camera LENS_FACING_FRONT verification failed
W/CameraValidator( 4994): java.lang.IllegalArgumentException: No available camera can be found
W/CameraValidator( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraValidator( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraValidator( 4994): 	at java.lang.Thread.run(Thread.java:923)
E/CameraValidator( 4994): Camera LensFacing verification failed, existing cameras: [Camera@4ce99e1[id=0]]
W/CameraX ( 4994): Retry init. Start time 22170954 current time 22173873
W/CameraX ( 4994): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:142)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4994): 	at java.lang.Thread.run(Thread.java:923)
W/CameraX ( 4994): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraX ( 4994): 	... 5 more
I/Camera2CameraInfo( 4994): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
W/CameraValidator( 4994): Camera LENS_FACING_FRONT verification failed
W/CameraValidator( 4994): java.lang.IllegalArgumentException: No available camera can be found
W/CameraValidator( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraValidator( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraValidator( 4994): 	at java.lang.Thread.run(Thread.java:923)
E/CameraValidator( 4994): Camera LensFacing verification failed, existing cameras: [Camera@5ba3f63[id=0]]
W/CameraX ( 4994): Retry init. Start time 22170954 current time 22174443
W/CameraX ( 4994): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:142)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4994): 	at java.lang.Thread.run(Thread.java:923)
W/CameraX ( 4994): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraX ( 4994): 	... 5 more
I/Camera2CameraInfo( 4994): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
W/CameraValidator( 4994): Camera LENS_FACING_FRONT verification failed
W/CameraValidator( 4994): java.lang.IllegalArgumentException: No available camera can be found
W/CameraValidator( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraValidator( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraValidator( 4994): 	at java.lang.Thread.run(Thread.java:923)
E/CameraValidator( 4994): Camera LensFacing verification failed, existing cameras: [Camera@a0bd51[id=0]]
W/CameraX ( 4994): Retry init. Start time 22170954 current time 22175011
W/CameraX ( 4994): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:142)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4994): 	at java.lang.Thread.run(Thread.java:923)
W/CameraX ( 4994): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraX ( 4994): 	... 5 more
I/Camera2CameraInfo( 4994): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
W/CameraValidator( 4994): Camera LENS_FACING_FRONT verification failed
W/CameraValidator( 4994): java.lang.IllegalArgumentException: No available camera can be found
W/CameraValidator( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraValidator( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraValidator( 4994): 	at java.lang.Thread.run(Thread.java:923)
E/CameraValidator( 4994): Camera LensFacing verification failed, existing cameras: [Camera@b133145[id=0]]
W/CameraX ( 4994): Retry init. Start time 22170954 current time 22175577
W/CameraX ( 4994): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:142)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4994): 	at java.lang.Thread.run(Thread.java:923)
W/CameraX ( 4994): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraX ( 4994): 	... 5 more
I/Camera2CameraInfo( 4994): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
W/CameraValidator( 4994): Camera LENS_FACING_FRONT verification failed
W/CameraValidator( 4994): java.lang.IllegalArgumentException: No available camera can be found
W/CameraValidator( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraValidator( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraValidator( 4994): 	at java.lang.Thread.run(Thread.java:923)
E/CameraValidator( 4994): Camera LensFacing verification failed, existing cameras: [Camera@a5522f9[id=0]]
W/CameraX ( 4994): Retry init. Start time 22170954 current time 22176147
W/CameraX ( 4994): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:142)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraX ( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4994): 	at java.lang.Thread.run(Thread.java:923)
W/CameraX ( 4994): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraX ( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraX ( 4994): 	... 5 more
I/Camera2CameraInfo( 4994): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
W/CameraValidator( 4994): Camera LENS_FACING_FRONT verification failed
W/CameraValidator( 4994): java.lang.IllegalArgumentException: No available camera can be found
W/CameraValidator( 4994): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:107)
W/CameraValidator( 4994): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:123)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:393)
W/CameraValidator( 4994): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraValidator( 4994): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraValidator( 4994): 	at java.lang.Thread.run(Thread.java:923)
E/CameraValidator( 4994): Camera LensFacing verification failed, existing cameras: [Camera@57d9c97[id=0]]
E/CameraX ( 4994): The device might underreport the amount of the cameras. Finish the initialize task since we are already reaching the maximum number of retries.
I/com.bqn.gpos( 4994): Background concurrent copying GC freed 50556(2499KB) AllocSpace objects, 11(576KB) LOS objects, 49% free, 4535KB/9071KB, paused 256us total 137.968ms
I/BufferQueueConsumer( 4994): [](id:138200000000,api:0,p:-1,c:4994) connect(): controlledByApp=true
I/BufferQueueConsumer( 4994): [](id:138200000001,api:0,p:-1,c:4994) connect(): controlledByApp=true
I/BufferQueueConsumer( 4994): [](id:138200000002,api:0,p:-1,c:4994) connect(): controlledByApp=true
I/BufferQueueProducer( 4994): [ImageReader-640x480f22m6-4994-2](id:138200000002,api:4,p:622,c:4994) connect(): api=4 producerControlledByApp=true
I/BufferQueueProducer( 4994): [ImageReader-1600x1200f23m4-4994-0](id:138200000000,api:4,p:622,c:4994) connect(): api=4 producerControlledByApp=false
D/ImageReaderSurfaceProducer( 4994): ImageTextureEntry can't wait on the fence on Android < 33
W/com.bqn.gpos( 4994): Verification of void com.google.android.gms.internal.mlkit_vision_common.zzhe.configure(com.google.firebase.encoders.config.EncoderConfig) took 164.869ms (5992.61 bytecodes/s) (23160B approximate peak alloc)
I/tflite  ( 4994): Initialized TensorFlow Lite runtime.
E/libc    ( 4994): Access denied finding property "ro.hardware.chipname"
I/tflite  ( 4994): Created TensorFlow Lite XNNPACK delegate for CPU.
I/tflite  ( 4994): Replacing 43 out of 43 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 1 partitions for the whole graph.
I/tflite  ( 4994): Replacing 35 out of 47 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 23 partitions for the whole graph.
I/native  ( 4994): I0000 00:00:1753362601.294840    5184 oned_decoder_client.cc:696] barhopper::deep_learning::OnedDecoderClient is created successfully.
W/GooglePlayServicesUtil( 4994): com.bqn.gpos requires the Google Play Store, but it is missing.
W/GoogleApiManager( 4994): The service for com.google.android.gms.common.internal.service.zap is not available: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
I/com.bqn.gpos( 4994): NativeAlloc concurrent copying GC freed 27950(3279KB) AllocSpace objects, 2(932KB) LOS objects, 49% free, 4820KB/9640KB, paused 266us total 135.181ms
```
