### ISSUE TITLE
 web: RangeError (index): Index out of range (Flutter 2/3)

### ISSUE THREAD

**Issue by i3games** [juliansteenbakker/mobile_scanner#143]
* Flutter 2 & 3
* mobile_scanner 1.1.0 
* `<script src="https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js"></script>`

This is thrown when a QR code is detected: 

```
Error: RangeError (index): Index out of range: index should be less than 5: 5
    at Object.throw_ [as throw] (http://localhost:60918/dart_sdk.js:5080:11)
    at Array.[dartx._get] (http://localhost:60918/dart_sdk.js:17547:21)
at Object.decode (http://localhost:60918/packages/utopien_player/model/encodings.dart.lib.js:672:365)
at scan._ScanScreenState.new.handleQrData (http://localhost:60918/packages/utopien_player/screens/scan.dart.lib.js:580:31)
at http://localhost:60918/packages/mobile_scanner/src/objects/barcode.dart.lib.js:2486:57
    at _RootZone.runUnaryGuarded (http://localhost:60918/dart_sdk.js:40448:11)
    at _BroadcastSubscription.new.[_sendData] (http://localhost:60918/dart_sdk.js:33985:22)
    at _DelayedData.new.perform (http://localhost:60918/dart_sdk.js:37447:28)
    at _StreamImplEvents.new.handleNext (http://localhost:60918/dart_sdk.js:37557:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60918/dart_sdk.js:37305:16)
    at Object._microtaskLoop (http://localhost:60918/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:60918/dart_sdk.js:40784:13)
    at http://localhost:60918/dart_sdk.js:36261:9
```

**Comment by i3games** [comment]
Seems not related to `mobile_scanner` but is thrown when an exception occurs within the `onDetect` callback
