### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException on QR read

### ISSUE THREAD

**Issue by luanemanuel** [juliansteenbakker/mobile_scanner#184]
# About

In some cases, on read a QR codes, the app crash and don't emit any log. In Firebase Crashlytics a event is emitted and a NullPointerException get logged.

# Exceptions:

### Xiaomi Mi 8 Lite:

```
Fatal Exception: java.lang.NullPointerException
       at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda-10$lambda-6(MobileScanner.java:12)
       at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$BscFLzaTHqafEwvwW6YKsVTE7Cs(MobileScanner.java)
       at dev.steenbakker.mobile_scanner.MobileScanner$$InternalSyntheticLambda$2$fe8e6235b54dd2e5f273769c4cadac104724e39a47fad3ccbe8c1fd84b785032$0.onSurfaceRequested(MobileScanner.java:4)
       at androidx.camera.core.Preview.lambda$sendSurfaceRequestIfReady$1(Preview.java)
       at androidx.camera.core.Preview.$r8$lambda$cQQSNpTD_vzDR540rq5dmfARJz4(Preview.java)
       at androidx.camera.core.Preview$$InternalSyntheticLambda$3$d61493696d1ee7326726a55caf5c13f9aac8b88e93d4b3aff0111862e82fce26$0.run(Preview.java:4)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7562)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

### Galaxy A22:

```
Fatal Exception: java.lang.NullPointerException
       at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda-10$lambda-6(MobileScanner.java:12)
       at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$BscFLzaTHqafEwvwW6YKsVTE7Cs(MobileScanner.java)
       at dev.steenbakker.mobile_scanner.MobileScanner$$InternalSyntheticLambda$2$fe8e6235b54dd2e5f273769c4cadac104724e39a47fad3ccbe8c1fd84b785032$0.onSurfaceRequested(MobileScanner.java:4)
       at androidx.camera.core.Preview.lambda$sendSurfaceRequestIfReady$1(Preview.java)
       at androidx.camera.core.Preview.$r8$lambda$cQQSNpTD_vzDR540rq5dmfARJz4(Preview.java)
       at androidx.camera.core.Preview$$InternalSyntheticLambda$3$d61493696d1ee7326726a55caf5c13f9aac8b88e93d4b3aff0111862e82fce26$0.run(Preview.java:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### POCO X3 PRO:

```
Fatal Exception: java.lang.NullPointerException
       at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda-10$lambda-6(MobileScanner.java:12)
       at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$BscFLzaTHqafEwvwW6YKsVTE7Cs(MobileScanner.java)
       at dev.steenbakker.mobile_scanner.MobileScanner$$InternalSyntheticLambda$2$fe8e6235b54dd2e5f273769c4cadac104724e39a47fad3ccbe8c1fd84b785032$0.onSurfaceRequested(MobileScanner.java:4)
       at androidx.camera.core.Preview.lambda$sendSurfaceRequestIfReady$1(Preview.java)
       at androidx.camera.core.Preview.$r8$lambda$cQQSNpTD_vzDR540rq5dmfARJz4(Preview.java)
       at androidx.camera.core.Preview$$InternalSyntheticLambda$3$d61493696d1ee7326726a55caf5c13f9aac8b88e93d4b3aff0111862e82fce26$0.run(Preview.java:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8250)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

# Implementation:

![image](https://user-images.githubusercontent.com/1703843/173123828-c24bddaf-1501-4717-b7e8-6cf525094385.png)

# Doctor

```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [versÆo 10.0.22000.675], locale pt-BR)
    • Flutter version 3.0.1 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\luane\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = C:\Users\luane\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\luane\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8609683\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Users\luane\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8609683
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Users\luane\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.5787.30
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22000.675]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 102.0.1245.33

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by juliansteenbakker** [comment]
Can you please try again with the latest version 3.0.0-beta.4? Please comment if this issue still exists with that version.
