### ISSUE TITLE
Error on release mode

### ISSUE THREAD

**Issue by Mahdi2565** [juliansteenbakker/mobile_scanner#249]
Hi ! 
this package works on debug mode well but when i want to get release apk i got this error : 

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mobile_scanner:mergeReleaseResources'.
> Could not resolve all files for configuration ':mobile_scanner:releaseRuntimeClasspath'.
   > Failed to transform exifinterface-1.3.2.aar (androidx.exifinterface:exifinterface:1.3.2) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find exifinterface-1.3.2.aar (androidx.exifinterface:exifinterface:1.3.2).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/exifinterface/exifinterface/1.3.2/exifinterface-1.3.2.aar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Running Gradle task 'assembleRelease'...                            4.1s
Exception: Gradle task assembleRelease failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:408:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:575:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:518:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:57:28)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:707:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

`
**flutter doctor** : 

`[✓] Flutter (Channel master, 3.1.0-0.0.pre.2142, on macOS 12.5 21G72 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.2142 on channel master at /Users/mohammadmahdinazer/Development/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a4947768b7 (22 hours ago), 2022-08-08 07:48:07 -0400
    • Engine revision dde62a46ec
    • Dart version 2.19.0 (build 2.19.0-74.0.dev)
    • DevTools version 2.16.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mohammadmahdinazer/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (4 available)
    • SM G965F (mobile)           • 2b5a3aba03027ece • android-arm64  • Android 10 (API 29)
    • sdk gphone64 arm64 (mobile) • emulator-5554    • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos            • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome           • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
`

**Comment by juliansteenbakker** [comment]
This issue is probably fixed with #257. I will release this as version 3.0.0 after i'm done with a few other functions

**Comment by adamstyrc** [comment]
Thanks @juliansteenbakker for including this change 🙌  let me know when you plan to release 3.0.0 to pub 8) Gonna use it immediately
