### ISSUE TITLE
App Crashed in android while using scanner with passbase package

### ISSUE THREAD

**Issue by bibash28** [juliansteenbakker/mobile_scanner#255]
Packages used combinely,
[passbase_flutter: ^2.13.3](https://pub.dev/packages/passbase_flutter/versions/2.13.3)
mobile_scanner: ^2.0.0

Crashing occurs only in Android... I use passbase package to take the selfie video. As soon as the video is opened the following error is encountered. This issue was not occurring with your old scanning package...

**Output:**

```
W/ActivityThread(24976): handleWindowVisibility: no activity for token android.os.BinderProxy@baa7b9c
D/LIFECYCLE_A(24976): LivenessManualActivity    onCreate()
D/LIFECYCLE_A(24976): LivenessManualActivity    onStart()
D/RenderScript HIDL Adaptation(24976): IRenderScriptDevice::getService()
D/vndksupport(24976): Loading /vendor/lib64/hw/android.hardware.renderscript@1.0-impl.so from current namespace instead of sphal namespace.
D/RenderScript HIDL Adaptation(24976): IRenderScriptDevice::getService() returned 0x767ac93200
D/RenderScript HIDL Adaptation(24976): HIDL successfully loaded.
V/RenderScript(24976): Successfully loaded runtime: libRSDriver_adreno.so
D/        (24976): Successfully queried cache dir: /data/user_de/0/co.altme.alt.me.altme/code_cache
D/RenderScript(24976): Setting cache dir: /data/user_de/0/co.altme.alt.me.altme/code_cache
D/FaceDetection(24976): ENCODE fps = 0.0
D/FaceDetection(24976): FACE DETECT fps = 0.0
I/DynamiteModule(24976): Considering local module com.google.mlkit.dynamite.face:10000 and remote module com.google.mlkit.dynamite.face:0
I/DynamiteModule(24976): Selected local version of com.google.mlkit.dynamite.face
D/TransportRuntime.SQLiteEventStore(24976): Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(24976): Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore(24976): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(24976): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/OnePlusJankManager(24976):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = co.altme.alt.me.altme/com.passbase.passbase_sdk.ui.liveness_check.LivenessScreen--- jank level = 1
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=6, fileFormat=2, videoCodec=2, videoBitRate=20000000, videoFrameRate=30, videoFrameWidth=1920, videoFrameHeight=1080, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=5, fileFormat=2, videoCodec=2, videoBitRate=14000000, videoFrameRate=30, videoFrameWidth=1280, videoFrameHeight=720, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=4, fileFormat=2, videoCodec=2, videoBitRate=2000000, videoFrameRate=30, videoFrameWidth=720, videoFrameHeight=480, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=6, fileFormat=2, videoCodec=2, videoBitRate=20000000, videoFrameRate=30, videoFrameWidth=1920, videoFrameHeight=1080, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=5, fileFormat=2, videoCodec=2, videoBitRate=14000000, videoFrameRate=30, videoFrameWidth=1280, videoFrameHeight=720, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=4, fileFormat=2, videoCodec=2, videoBitRate=2000000, videoFrameRate=30, videoFrameWidth=720, videoFrameHeight=480, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/QualitySelector(24976): supportedQualities = [ConstantQuality{value=6, name=FHD}, ConstantQuality{value=5, name=HD}, ConstantQuality{value=4, name=SD}]
D/QualitySelector(24976): Select quality by fallbackStrategy = RuleStrategy{fallbackQuality=ConstantQuality{value=-1, name=NONE}, fallbackRule=0}
D/VideoCapture(24976): Found selectedQualities [ConstantQuality{value=4, name=SD}] by QualitySelector{preferredQualities=[ConstantQuality{value=4, name=SD}], fallbackStrategy=RuleStrategy{fallbackQuality=ConstantQuality{value=-1, name=NONE}, fallbackRule=0}}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=6, fileFormat=2, videoCodec=2, videoBitRate=20000000, videoFrameRate=30, videoFrameWidth=1920, videoFrameHeight=1080, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=5, fileFormat=2, videoCodec=2, videoBitRate=14000000, videoFrameRate=30, videoFrameWidth=1280, videoFrameHeight=720, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=4, fileFormat=2, videoCodec=2, videoBitRate=2000000, videoFrameRate=30, videoFrameWidth=720, videoFrameHeight=480, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapture(24976): Set supported resolutions = [720x480]
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=6, fileFormat=2, videoCodec=2, videoBitRate=20000000, videoFrameRate=30, videoFrameWidth=1920, videoFrameHeight=1080, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=5, fileFormat=2, videoCodec=2, videoBitRate=14000000, videoFrameRate=30, videoFrameWidth=1280, videoFrameHeight=720, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=4, fileFormat=2, videoCodec=2, videoBitRate=2000000, videoFrameRate=30, videoFrameWidth=720, videoFrameHeight=480, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=6, fileFormat=2, videoCodec=2, videoBitRate=20000000, videoFrameRate=30, videoFrameWidth=1920, videoFrameHeight=1080, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=5, fileFormat=2, videoCodec=2, videoBitRate=14000000, videoFrameRate=30, videoFrameWidth=1280, videoFrameHeight=720, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=4, fileFormat=2, videoCodec=2, videoBitRate=2000000, videoFrameRate=30, videoFrameWidth=720, videoFrameHeight=480, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/QualitySelector(24976): supportedQualities = [ConstantQuality{value=6, name=FHD}, ConstantQuality{value=5, name=HD}, ConstantQuality{value=4, name=SD}]
D/QualitySelector(24976): Select quality by fallbackStrategy = RuleStrategy{fallbackQuality=ConstantQuality{value=-1, name=NONE}, fallbackRule=0}
D/VideoCapture(24976): Found selectedQualities [ConstantQuality{value=4, name=SD}] by QualitySelector{preferredQualities=[ConstantQuality{value=4, name=SD}], fallbackStrategy=RuleStrategy{fallbackQuality=ConstantQuality{value=-1, name=NONE}, fallbackRule=0}}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=6, fileFormat=2, videoCodec=2, videoBitRate=20000000, videoFrameRate=30, videoFrameWidth=1920, videoFrameHeight=1080, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=5, fileFormat=2, videoCodec=2, videoBitRate=14000000, videoFrameRate=30, videoFrameWidth=1280, videoFrameHeight=720, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=4, fileFormat=2, videoCodec=2, videoBitRate=2000000, videoFrameRate=30, videoFrameWidth=720, videoFrameHeight=480, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapture(24976): Set supported resolutions = [720x480]
D/VideoCapture(24976): suggestedResolution = 720x480
D/DeferrableSurface(24976): Surface created[total_surfaces=1, used_surfaces=0](androidx.camera.core.SurfaceRequest$2@492b578}
D/Recorder(24976): Surface is requested in state: INITIALIZING, Current surface: 0
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=6, fileFormat=2, videoCodec=2, videoBitRate=20000000, videoFrameRate=30, videoFrameWidth=1920, videoFrameHeight=1080, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=5, fileFormat=2, videoCodec=2, videoBitRate=14000000, videoFrameRate=30, videoFrameWidth=1280, videoFrameHeight=720, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/CameraOrientationUtil(24976): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
D/VideoCapabilities(24976): profile = CamcorderProfileProxy{duration=30, quality=4, fileFormat=2, videoCodec=2, videoBitRate=2000000, videoFrameRate=30, videoFrameWidth=720, videoFrameHeight=480, audioCodec=3, audioBitRate=156000, audioSampleRate=48000, audioChannels=2}
D/Recorder(24976): Using supported quality of ConstantQuality{value=4, name=SD} for surface size 720x480
D/Recorder(24976): MediaSpec contains OUTPUT_FORMAT_AUTO. Using CamcorderProfile to derive VIDEO settings [mime type: video/avc]
D/VideoConfigUtil(24976): Using single supported VIDEO frame rate: 30
D/VidEncCmcrdrPrflRslvr(24976): Using resolved VIDEO bitrate from CamcorderProfile
D/VideoConfigUtil(24976): Base Bitrate(2000000bps) * Frame Rate Ratio(30 / 30) * Width Ratio(720 / 720) * Height Ratio(480 / 480) = 2000000
D/AndroidRuntime(24976): Shutting down VM
E/AndroidRuntime(25010): FATAL EXCEPTION: main
E/AndroidRuntime(25010): Process: co.altme.alt.me.altme, PID: 25010
E/AndroidRuntime(25010): java.lang.NoSuchMethodError: No virtual method addErrorListener(Landroidx/camera/core/impl/SessionConfig$ErrorListener;)V in class Landroidx/camera/core/impl/SessionConfig$Builder; or its super classes (declaration of 'androidx.camera.core.impl.SessionConfig$Builder' appears in /data/app/co.altme.alt.me.altme-h-frsNiEvJ0nAM8y96sCCQ==/base.apk)
E/AndroidRuntime(25010):        at androidx.camera.video.VideoCapture.createPipeline(VideoCapture.java:429)
E/AndroidRuntime(25010):        at androidx.camera.video.VideoCapture.onSuggestedResolutionUpdated(VideoCapture.java:277)
E/AndroidRuntime(25010):        at androidx.camera.core.UseCase.updateSuggestedResolution(UseCase.java:523)
E/AndroidRuntime(25010):        at androidx.camera.core.internal.CameraUseCaseAdapter.addUseCases(CameraUseCaseAdapter.java:240)
E/AndroidRuntime(25010):        at androidx.camera.lifecycle.LifecycleCamera.bind(LifecycleCamera.java:206)
E/AndroidRuntime(25010):        at androidx.camera.lifecycle.LifecycleCameraRepository.bindToLifecycleCamera(LifecycleCameraRepository.java:278)
E/AndroidRuntime(25010):        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:532)
E/AndroidRuntime(25010):        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:360)
E/AndroidRuntime(25010):        at com.passbase.passbase_sdk.ui.liveness_check.CameraXService.init$lambda-2(CameraXService.kt:120)
E/AndroidRuntime(25010):        at com.passbase.passbase_sdk.ui.liveness_check.CameraXService.lambda$vRvR2xxpTvTU767hp2TYJrjW3R4(Unknown Source:0)
E/AndroidRuntime(25010):        at com.passbase.passbase_sdk.ui.liveness_check.-$$Lambda$CameraXService$vRvR2xxpTvTU767hp2TYJrjW3R4.run(Unknown Source:8)
E/AndroidRuntime(25010):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(25010):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25010):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(25010):        at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime(25010):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25010):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(25010):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(24976): FATAL EXCEPTION: main
E/AndroidRuntime(24976): Process: co.altme.alt.me.altme, PID: 24976
E/AndroidRuntime(24976): java.lang.NoSuchMethodError: No virtual method addErrorListener(Landroidx/camera/core/impl/SessionConfig$ErrorListener;)V in class Landroidx/camera/core/impl/SessionConfig$Builder; or its super classes (declaration of 'androidx.camera.core.impl.SessionConfig$Builder' appears in /data/app/co.altme.alt.me.altme-h-frsNiEvJ0nAM8y96sCCQ==/base.apk)
E/AndroidRuntime(24976):        at androidx.camera.video.VideoCapture.createPipeline(VideoCapture.java:429)
E/AndroidRuntime(24976):        at androidx.camera.video.VideoCapture.onSuggestedResolutionUpdated(VideoCapture.java:277)
E/AndroidRuntime(24976):        at androidx.camera.core.UseCase.updateSuggestedResolution(UseCase.java:523)
E/AndroidRuntime(24976):        at androidx.camera.core.internal.CameraUseCaseAdapter.addUseCases(CameraUseCaseAdapter.java:240)
E/AndroidRuntime(24976):        at androidx.camera.lifecycle.LifecycleCamera.bind(LifecycleCamera.java:206)
E/AndroidRuntime(24976):        at androidx.camera.lifecycle.LifecycleCameraRepository.bindToLifecycleCamera(LifecycleCameraRepository.java:278)
E/AndroidRuntime(24976):        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:532)
E/AndroidRuntime(24976):        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:360)
E/AndroidRuntime(24976):        at com.passbase.passbase_sdk.ui.liveness_check.CameraXService.init$lambda-2(CameraXService.kt:120)
E/AndroidRuntime(24976):        at com.passbase.passbase_sdk.ui.liveness_check.CameraXService.lambda$vRvR2xxpTvTU767hp2TYJrjW3R4(Unknown Source:0)
E/AndroidRuntime(24976):        at com.passbase.passbase_sdk.ui.liveness_check.-$$Lambda$CameraXService$vRvR2xxpTvTU767hp2TYJrjW3R4.run(Unknown Source:8)
E/AndroidRuntime(24976):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(24976):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24976):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(24976):        at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime(24976):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24976):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(24976):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/VideoEncoder(24976): mMediaFormat = {color-format=2130708361, i-frame-interval=1, mime=video/avc, width=720, bitrate=2000000, frame-rate=30, height=480}
W/OPDiagnose(24976): getService:OPDiagnoseService NULL
D/OSTracker(24976): OS Event: crash
W/VideoCapabilities(24976): Unsupported mime video/divx
W/VideoCapabilities(24976): Unsupported mime video/divx311
W/VideoCapabilities(24976): Unsupported mime video/divx4
D/AbstractTracker(24976): Event success
I/Process (24976): Sending signal. PID: 24976 SIG: 9
Lost connection to device.
```

**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by bibash28** [comment]
Thanks a lot..

**Comment by juliansteenbakker** [comment]
I will release this as version 3.0.0 after i'm done with a few other functions
