### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by vyendn3** [juliansteenbakker/mobile_scanner#354]
`Fatal Exception: java.lang.NoSuchFieldError: No static field ANALYSIS of type Landroidx/camera/core/impl/SurfaceConfig$ConfigSize; in class Landroidx/camera/core/impl/SurfaceConfig$ConfigSize; or its superclasses (declaration of 'androidx.camera.core.impl.SurfaceConfig$ConfigSize' appears in /data/app/~~PjnaF-sv2M6wLmOla63yjA==/net.vinhms.cihms.staff-wfruSJMHi2UFY5DSzbG4uw==/base.apk)
       at androidx.camera.camera2.internal.compat.quirk.ExtraSupportedSurfaceCombinationsQuirk.createFullYuvPrivYuvConfiguration(ExtraSupportedSurfaceCombinationsQuirk.java:277)
       at androidx.camera.camera2.internal.compat.quirk.ExtraSupportedSurfaceCombinationsQuirk.<clinit>(ExtraSupportedSurfaceCombinationsQuirk.java:54)
       at androidx.camera.camera2.internal.compat.quirk.ExtraSupportedSurfaceCombinationsQuirk.load(ExtraSupportedSurfaceCombinationsQuirk.java:211)
       at androidx.camera.camera2.internal.compat.quirk.DeviceQuirksLoader.loadQuirks(DeviceQuirksLoader.java:65)
       at androidx.camera.camera2.internal.compat.quirk.DeviceQuirks.<clinit>(DeviceQuirks.java:41)
       at androidx.camera.camera2.internal.compat.quirk.DeviceQuirks.get(DeviceQuirks.java:62)
       at androidx.camera.camera2.internal.compat.workaround.MaxPreviewSize.<init>(MaxPreviewSize.java:44)
       at androidx.camera.camera2.internal.DisplayInfoManager.<init>(DisplayInfoManager.java:41)
       at androidx.camera.camera2.internal.DisplayInfoManager.getInstance(DisplayInfoManager.java:55)
       at androidx.camera.camera2.internal.Camera2CameraFactory.<init>(Camera2CameraFactory.java:67)
       at androidx.camera.camera2.Camera2Config$$InternalSyntheticLambda$1$b737bf8082c5f7ea267385a154eefca2640a55b974e0d2599d3c3cd43ba9dca3$0.newInstance(Camera2Config.java:2)
       at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2(CameraX.java:312)
       at androidx.camera.core.CameraX.$r8$lambda$dnuYhxGsACX_lH-9SVlUVTdtTJg(CameraX.java)
       at androidx.camera.core.CameraX$$InternalSyntheticLambda$6$845f10987ef598ac292769067d92d63fd4aa661f29de3bb3ed47d03f5eaa76ed$0.run(CameraX.java:10)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)`

**Comment by vyendn3** [comment]
My mistake
