### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Provided camera selector unable to resolve a camera for the given use case

### ISSUE THREAD

**Issue by paveljoffe** [juliansteenbakker/mobile_scanner#360]
Fatal Exception: java.lang.IllegalArgumentException: Provided camera selector unable to resolve a camera for the given use case
       at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:250)
       at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:1)
       at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda-10(MobileScanner.java:155)
       at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$sabvDajmNHk5NsaaoXEm5J9v-QY(MobileScanner.java)
       at dev.steenbakker.mobile_scanner.MobileScanner$$InternalSyntheticLambda$1$dbc15e1b9c39688e170cd7b502ebdfd19b8a6801e77f22e88b73084ed7fa6a9d$0.run(MobileScanner.java:14)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by AathifMahir** [comment]
@juliansteenbakker anything on this issue?

**Comment by dleurs** [comment]
Same here on mobile_scanner 2.0.0, on Android 11, Redmi Note 10, on december 2022

```
Fatal Exception: java.lang.IllegalArgumentException: Provided camera selector unable to resolve a camera for the given use case
       at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:470)
       at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:360)
       at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda-10(MobileScanner.kt:190)
       at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$sabvDajmNHk5NsaaoXEm5J9v-QY(MobileScanner.kt)
       at dev.steenbakker.mobile_scanner.MobileScanner$$InternalSyntheticLambda$0$dbc15e1b9c39688e170cd7b502ebdfd19b8a6801e77f22e88b73084ed7fa6a9d$0.run(MobileScanner.java:14)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8019)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by GhxstlyJared** [comment]
Same here on 3.0.0-beta4. Occurs from 6 android and above

**Comment by GhxstlyJared** [comment]
Are there any updates on the issue? Still running into this issue on most devices

**Comment by p3pp8** [comment]
3.2.0 as well. Many crashes with same reason. Any news about this issue? Any workaround? Help is really appreciated !!!

**Comment by juliansteenbakker** [comment]
I'm closing this as there are newer versions of this plug already released. If this still happens with the latest version let me know by commenting.
