### ISSUE TITLE
[bug] Denying camera permission results in a deadlock on the permission request

### ISSUE THREAD

**Issue by navaronbracke** [juliansteenbakker/mobile_scanner#402]
When running the example app, I noticed that there is a bug with the permission request on Android.
I have not tested this on iOS, so I don't know if it occurs there too.

### Steps to reproduce

1. Clone the master branch
2. Run the example app on an Android device `cd example && flutter run -d my_android_device`
3. Press the `Mobile Scanner with controller` button
4. The permission popup appears with `Allow` & `Deny`
5. Press `Deny`
6. The permission popup reappears, but now with the options `Allow`, `Deny`, `Deny and don't ask again`
7.  Press `Deny`
8. The permission popup reappears as in step 6, until you either press `Allow` or `Deny and don't ask again`
9. If you press `Deny and don't ask again` the app enters a deadlock, as I cannot swipe up to open the application switcher
10. If you press `Allow` the app runs as expected

To debug step 9, I added logs around the native code that requests the permission. I see that the permission request logs are infinitely repeating.

Specifically the following lines repeat:
- https://github.com/juliansteenbakker/mobile_scanner/blob/master/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt#L94
- https://github.com/juliansteenbakker/mobile_scanner/blob/master/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt#L109

In the logs I can also see that the permission method call keeps returning an error result, despite only calling `await controller.start()` only once. I expect exactly one method call result.

Side note: The example app does not handle the `MobileScannerException` for the denied permission, but that is besides the point here.

<details>
  <summary>Logs</summary>

```
E/flutter ( 9931): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MobileScannerException: permissionDenied
E/flutter ( 9931): #0      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:166:13)
E/flutter ( 9931): <asynchronous suspension>
E/flutter ( 9931): 
E/flutter ( 9931): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MobileScannerException: permissionDenied
E/flutter ( 9931): #0      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:166:13)
E/flutter ( 9931): <asynchronous suspension>
E/flutter ( 9931): 
E/flutter ( 9931): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MobileScannerException: permissionDenied
E/flutter ( 9931): #0      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:166:13)
E/flutter ( 9931): <asynchronous suspension>
E/flutter ( 9931): 
E/flutter ( 9931): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MobileScannerException: permissionDenied
E/flutter ( 9931): #0      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:166:13)
E/flutter ( 9931): <asynchronous suspension>
E/flutter ( 9931): 
E/flutter ( 9931): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MobileScannerException: permissionDenied
E/flutter ( 9931): #0      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:166:13)
E/flutter ( 9931): <asynchronous suspension>
E/flutter ( 9931): 
E/flutter ( 9931): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MobileScannerException: permissionDenied
E/flutter ( 9931): #0      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:166:13)
E/flutter ( 9931): <asynchronous suspension>
E/flutter ( 9931): 
E/flutter ( 9931): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MobileScannerException: permissionDenied
E/flutter ( 9931): #0      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:166:13)
E/flutter ( 9931): <asynchronous suspension>
E/flutter ( 9931): 
E/flutter ( 9931): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MobileScannerException: permissionDenied
E/flutter ( 9931): #0      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:166:13)
E/flutter ( 9931): <asynchronous suspension>
E/flutter ( 9931): 
E/flutter ( 9931): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MobileScannerException: permissionDenied
E/flutter ( 9931): #0      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:166:13)
E/flutter ( 9931): <asynchronous suspension>
E/flutter ( 9931): 

// The same error message keeps repeating until I kill the app using 'q' in the terminal
```
<details/>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.2.1 21D62 darwin-x64, locale en-BE)
    • Flutter version 3.3.8 on channel stable at /Users/navaronbracke/Documents/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 52b3dc25f6 (4 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/navaronbracke/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/navaronbracke/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • motorola one (mobile) • ZL5228NFL7 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)       • macos      • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)          • chrome     • web-javascript • Google Chrome 108.0.5359.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

<details/>

**Comment by navaronbracke** [comment]
@juliansteenbakker I looked at how `camera` handles the camera permissions.

Apparently, they do two things:
- manage an ongoing flag
- abort the permission request if already called

Perhaps we could reuse that implementation?

Reference: 
https://github.com/flutter/plugins/blob/main/packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java
