### ISSUE TITLE
Exception when using .analyzeImage in v3.0.0-beta.4

### ISSUE THREAD

**Issue by iklochko** [juliansteenbakker/mobile_scanner#423]
iOS
Trying to execute:
```
MobileScannerController barcodeCameraController = MobileScannerController(formats: [BarcodeFormat.upcA]);
late StreamSubscription barcodesStreamSubscription;

...

barcodesStreamSubscription = barcodeCameraController.barcodes.listen((capture) {
      capture.barcodes.forEach((barcode) {
        print('CAM: ${barcode.rawValue}');
      });
      barcodesStreamSubscription.cancel();
    });

    await barcodeCameraController.analyzeImage(_myImgFile.path);

```
Get exception.
```
flutter: type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'List<dynamic>' in type cast
flutter: 
#0      MobileScannerController._handleEvent (package:mobile_scanner/src/mobile_scanner_controller.dart:349:30)
#1      new MobileScannerController.<anonymous closure> (package:mobile_scanner/src/mobile_scanner_controller.dart:31:27)
#2      _rootRunUnary (dart:async/zone.dart:1399:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1300:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#7      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#9      _rootRun (dart:async/zone.dart:1383:47)
#10     _CustomZone.run (dart:async/zone.dart:1293:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1241:23)
#13     _rootRun (dart:async/zone.dart:1391:13)
#14     _CustomZone.run (dart:async/zone.dart:1293:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1241:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

Noticed that in mobile_scanner_controller.dart
```
case 'barcode':
        if (data == null) return;
        final parsed = (data as List)
            .map((value) => Barcode.fromNative(value as Map))
            .toList();
```
When scanning with camera data is list, and when with analyzeImage it's a single element of the list.

**Comment by jxstxn1** [comment]
Facing the same Error. Tried to get the BarCode out of the Controller after `analyzeImage` returned `true`

**Comment by juliansteenbakker** [comment]
Can you please try again with version 3.0.0?

**Comment by jxstxn1** [comment]
Tried it but its not really working
Its just not detecting any QR Codes which are detected without problems in the camera
