### ISSUE TITLE
Crash Android RuntimeException ResultInfo and ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dleurs** [juliansteenbakker/mobile_scanner#440]
Hello :) 

I detected a crash with Google Crashlytics from mobile_scanner 2.0.0, on Android 11, Redmi Note 10 Pro and Android 12, Galaxy A13 5G, on decembre 2022 : 

```
 MobileScanner.kt line 86
```
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=22022022, result=0, data=null} to activity {com.tao.mytao/com.tao.mytao.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5946)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5985)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
```
Caused by java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at dev.steenbakker.mobile_scanner.MobileScanner.requestPermission$lambda-0(MobileScanner.kt:86)
       at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$QpUV_Cf6UTOHhJ2jK0mCWvPJnQI(MobileScanner.kt)
       at dev.steenbakker.mobile_scanner.MobileScanner$$InternalSyntheticLambda$0$e09502981050d625ecf594773ac76c7d9246fc158cfbc8e914f3647beb81515d$0.onRequestPermissionsResult(MobileScanner.java:4)
       at dev.steenbakker.mobile_scanner.MobileScanner.onRequestPermissionsResult(MobileScanner.kt:70)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:757)
       at io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult(FlutterFragment.java:915)
       at io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult(FlutterFragmentActivity.java:549)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8833)
       at android.app.Activity.dispatchActivityResult(Activity.java:8663)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5939)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5985)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by juliansteenbakker** [comment]
Can you please try this again with version 3.0.0?

**Comment by rohansohonee1** [comment]
Facing issue with version 3.0.0-beta.1

```
Caused by java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at dev.steenbakker.mobile_scanner.MobileScanner.requestPermission$lambda$0(MobileScanner.kt:90)
       at dev.steenbakker.mobile_scanner.MobileScanner.onRequestPermissionsResult(MobileScanner.kt:74)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:781)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:413)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:820)
       at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:941)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7631)
       at android.app.Activity.dispatchActivityResult(Activity.java:7481)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4539)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4588)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:205)
       at android.app.ActivityThread.main(ActivityThread.java:6993)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```
