### ISSUE TITLE
Android: mobile_scanner 3.0.0 crashes on scan 

### ISSUE THREAD

**Issue by ViliusP** [juliansteenbakker/mobile_scanner#480]
I did not try on iOS or other platforms.

Steps to reproduce:

1. Run code on Android. Crash also occurs on simulator (configure to use webcam as simulator camera).
2. Try to scan.
2.1. Scan QR code with some data. For example "3354". (https://www.qr-code-generator.com/ can be used).
2.2. Barcode scanning is also crashing. ([Generate Free Barcodes Online](https://barcode.tec-it.com/en) can be used to generate barcode).
3. You should see exception like below.

Logs
```text
E/flutter ( 7425): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<Barcode>'
E/flutter ( 7425): #0      MobileScannerController._handleEvent
mobile_scanner_controller.dart:343
E/flutter ( 7425): #1      MobileScannerController.start.<anonymous closure>
mobile_scanner_controller.dart:157
E/flutter ( 7425): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter ( 7425): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 7425): #4      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter ( 7425): #5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter ( 7425): #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter ( 7425): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 7425): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

<details>
  <summary>Code (taken from example):</summary>
  
```dart
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Mobile Scanner')),
      body: MobileScanner(
        // fit: BoxFit.contain,
        onDetect: (capture) {
          final List<Barcode> barcodes = capture.barcodes;
          final Uint8List? image = capture.image;
          for (final barcode in barcodes) {
            debugPrint('Barcode found! ${barcode.rawValue}');
          }
        },
      ),
    );
  }
}
  ```
</details>

<details>
  <summary>Flutter doctor -v</summary>
  
  ```bash
  [✓] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-arm64, locale en-LT)
    • Flutter version 3.7.3 on channel stable at /Users/viliuspaliokas/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (2 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/viliuspaliokas/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/viliuspaliokas/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Users/viliuspaliokas/Downloads/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • GM1901 (mobile) • a42ac092 • android-arm64  • Android 13 (API 33)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
  ```
</details>

**Comment by ViliusP** [comment]
Somehow bug resolved itself after running `flutter pub cache clean`.
