### ISSUE TITLE
Constraints in LayoutBuilder sometimes zero

### ISSUE THREAD

**Issue by frankvollebregt** [juliansteenbakker/mobile_scanner#574]
I was experiencing crashes on a Samsung Galaxy S21 running Android 13 (sometimes the system would report that the app is buggy, other times it would just crash outright). I did not experience this on a number of other devices including a Pixel 7, Pixel 2, Samsung Tab S5e, Samsung S9+. This stacktrace is printed to the console:

<details>
<summary>Original Stacktrace</summary>

```
E/AndroidRuntime(16076): java.lang.IllegalArgumentException: Cannot round NaN value.
E/AndroidRuntime(16076): 	at o4.c.a(Unknown Source:15)
E/AndroidRuntime(16076): 	at o4.a.a(Unknown Source:0)
E/AndroidRuntime(16076): 	at i3.q.t(Unknown Source:124)
E/AndroidRuntime(16076): 	at i3.q.p(Unknown Source:112)
E/AndroidRuntime(16076): 	at i3.q.c(Unknown Source:0)
E/AndroidRuntime(16076): 	at i3.p.b(Unknown Source:8)
E/AndroidRuntime(16076): 	at k2.z.run(Unknown Source:25)
E/AndroidRuntime(16076): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(16076): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16076): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(16076): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(16076): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(16076): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16076): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(16076): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
</details>

Which is obfuscated so not terribly helpful. Luckily, the google play console pointed me to the culprit: [this line in MobileScanner.kt](https://github.com/juliansteenbakker/mobile_scanner/blob/6035379cc2dbb5a7707354299a7a902f8f106cf9/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt#L121), which would turn out to become `NaN` when being rounded. After doing some more debugging, it turns out to be a result of the [Size of the constraints in the layout builder](https://github.com/juliansteenbakker/mobile_scanner/blob/6035379cc2dbb5a7707354299a7a902f8f106cf9/lib/src/mobile_scanner.dart#L249) being set to 0.0. Then, while calculating the window, there is a division by this size resulting in the `NaN` value.

I've thought about some different solutions to this issue: setting the size to a minimum of 1 would prevent the error, but this would only work if the `LayoutBuilder` automatically rebuilds when its constraints change (that is, once the actual Widget is rendered, it is recalculated), and I'm not sure how that works.

Let me know your thoughts. Thanks :)

**Comment by frankvollebregt** [comment]
After testing a bit with the "solution" I proposed above, it seems like the 1x1 size is never updated once the actual Widget is displayed, and as a result I'm not able to scan codes during that "run".

My `MobileScanner` is located in a `CustomPaint` (for the overlay) in a `Stack` in a `SafeArea` in the `Scaffold.body`.

**Comment by navaronbracke** [comment]
Interesting find. AFAIK some devices only report an initial display size after the first frame, but I don't think that this could be the issue. What if we just return "false" for that check if the incoming sizes are zero ?

**Comment by juliansteenbakker** [comment]
I'm closing this as there is no activity, and newer versions of this plug are already released. If this still happens with the latest version let me know by commenting.
