### ISSUE TITLE
NPE @  MobileScanner.start$lambda-12$lambda-7(MobileScanner.java:12)

### ISSUE THREAD

**Issue by p3pp8** [juliansteenbakker/mobile_scanner#628]
Hello, 

I'm receiving many nullPointerExeception from crashlytics, this is the stackTrace:

```
Fatal Exception: java.lang.NullPointerException:
       at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda-12$lambda-7(MobileScanner.java:12)
       at androidx.camera.core.Preview.lambda$sendSurfaceRequest$1(Preview.java)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by teolemon** [comment]
Could you add reproduction steps ?

**Comment by ebragaparah** [comment]
We are facing a related issue on our latest releases. I caught this on our Crashlytics.

```
Fatal Exception: java.lang.NullPointerException:
       at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda-10$lambda-6(MobileScanner.kt:166)
       at dev.steenbakker.mobile_scanner.MobileScanner.lambda$BscFLzaTHqafEwvwW6YKsVTE7Cs()
       at dev.steenbakker.mobile_scanner.-$$Lambda$MobileScanner$BscFLzaTHqafEwvwW6YKsVTE7Cs.onSurfaceRequested(:4)
       at androidx.camera.core.Preview.lambda$sendSurfaceRequestIfReady$1(Preview.java:391)
       at androidx.camera.core.-$$Lambda$Preview$cQQSNpTD_vzDR540rq5dmfARJz4.run(:4)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by p3pp8** [comment]
@teolemon unfortunately i'm not able to reproduce the crash, what i see are Google crashlytics events sent from users devices experiencing crashes with mobile_scanner using our application.

**Comment by amonizaone** [comment]
I also faced the same problem in crashlytics

Exception java.lang.NullPointerException:
  at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda$10$lambda$6 (MobileScanner.kt:171)
  at androidx.camera.core.Preview.lambda$sendSurfaceRequest$1 (Preview.java:516)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8645)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

**Comment by rodrigopequeno** [comment]
I believe it is the same error but we are having a problem with deobfuscation. This error occurs in only 1% of sessions and has a higher frequency in OS version 11. Unfortunately I couldn't play either.

```
java.lang.NullPointerException: Application crash detected: java.lang.NullPointerException
java.lang.NullPointerException
	at f8.q.z(MobileScanner.kt:1)
	at f8.q.b(Unknown Source:0)
	at f8.h.a(Unknown Source:4)
	at androidx.camera.core.c2.S(Preview.java:1)
	at androidx.camera.core.c2.L(Unknown Source:0)
	at androidx.camera.core.a2.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by navaronbracke** [comment]
@rodrigopequeno Does this still happen in version 3.5.2 ?

**Comment by rodrigopequeno** [comment]
Hi @navaronbracke, I will update the version and update here when I have news. Thanks in advance.

**Comment by navaronbracke** [comment]
@rodrigopequeno Do you still experience this issue?

**Comment by rodrigopequeno** [comment]
Hi @navaronbracke, I'm no longer facing this problem. I believe it has been resolved. Thanks a lot for the help.
