### ISSUE TITLE
Handle Case With Only One Camera

### ISSUE THREAD

**Issue by p0wl90** [juliansteenbakker/mobile_scanner#66]
Hey! Thanks for implementing this great package! I found a bug with devices that only have one camera:

1. Create an Android Emulator with only a backward camera
2. Use your _Example with controller and torch & camera controls_
3. Run the app and toggle the camera switch button

Expected: It does not work and there is some API to find out about the camera count
Actual: An exception is thrown when starting the scanner and one when toggling the camera

### Exception that occurs 5x when starting the scanner 
```
I/CameraManagerGlobal( 6751): Connecting to camera service
D/CameraRepository( 6751): Added camera: 0
I/Camera2CameraInfo( 6751): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraValidator( 6751): Verifying camera lens facing on generic_x86_arm, lensFacingInteger: null
E/CameraValidator( 6751): Camera LensFacing verification failed, existing cameras: [Camera@d8b98e[id=0]]
W/CameraX ( 6751): Retry init. Start time 438289 current time 438313
W/CameraX ( 6751): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 6751): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:97)
W/CameraX ( 6751): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$CameraX(CameraX.java:341)
W/CameraX ( 6751): 	at androidx.camera.core.-$$Lambda$CameraX$KfzLCXuIc-FzgKWqE1UYH1CITHc.run(Unknown Source:10)
W/CameraX ( 6751): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 6751): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 6751): 	at java.lang.Thread.run(Thread.java:923)
W/CameraX ( 6751): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 6751): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:82)
W/CameraX ( 6751): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:91)
W/CameraX ( 6751): 	... 5 more
```

### Exception that occurs when toggling the camera
```
D/DeferrableSurface( 8552): surface closed,  useCount=1 closed=true androidx.camera.core.SurfaceRequest$2@2eee9d4
D/DeferrableSurface( 8552): surface closed,  useCount=1 closed=true androidx.camera.core.impl.ImmediateSurface@a2b2ac3
D/Camera2CameraImpl( 8552): {Camera@28d60e0[id=0]} Use cases [androidx.camera.core.Preview-50b005b9-2938-43f5-b0c7-29048bc352da134173893, androidx.camera.core.ImageAnalysis-e2501c91-db0b-4269-b2cf-4d1ededc01d7149507610] now DETACHED for camera
D/UseCaseAttachState( 8552): All use case: [] for camera: 0
D/Camera2CameraImpl( 8552): {Camera@28d60e0[id=0]} Resetting Capture Session
D/Camera2CameraImpl( 8552): {Camera@28d60e0[id=0]} Releasing session in state OPENED
D/UseCaseAttachState( 8552): Active and attached use case: [] for camera: 0
D/UseCaseAttachState( 8552): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl( 8552): {Camera@28d60e0[id=0]} Closing camera.
D/Camera2CameraImpl( 8552): {Camera@28d60e0[id=0]} Transitioning camera internal state: OPENED --> CLOSING
D/CameraStateRegistry( 8552): Recalculating open cameras:
D/CameraStateRegistry( 8552): Camera                                       State
D/CameraStateRegistry( 8552): -------------------------------------------------------------------
D/CameraStateRegistry( 8552): Camera@28d60e0[id=0]                         CLOSING
D/CameraStateRegistry( 8552): -------------------------------------------------------------------
D/CameraStateRegistry( 8552): Open count: 1 (Max allowed: 1)
D/CameraStateMachine( 8552): New public camera state CameraState{type=CLOSING, error=null} from CLOSING and null
D/CameraStateMachine( 8552): Publishing new public camera state CameraState{type=CLOSING, error=null}
D/Camera2CameraImpl( 8552): {Camera@28d60e0[id=0]} Resetting Capture Session
D/Camera2CameraImpl( 8552): {Camera@28d60e0[id=0]} Releasing session in state CLOSING
D/CaptureSession( 8552): onSessionFinished()
E/BufferQueueProducer( 8552): [SurfaceTexture-0-8552-0](id:216800000000,api:4,p:396,c:8552) queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 8552): [SurfaceTexture-0-8552-0](id:216800000000,api:4,p:396,c:8552) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 8552): [SurfaceTexture-0-8552-0](id:216800000000,api:4,p:396,c:8552) queueBuffer: BufferQueue has been abandoned
D/AndroidRuntime( 8552): Shutting down VM
E/AndroidRuntime( 8552): FATAL EXCEPTION: main
E/AndroidRuntime( 8552): Process: de.xyz.abc, PID: 8552
E/AndroidRuntime( 8552): java.lang.IllegalArgumentException: Provided camera selector unable to resolve a camera for the given use case
E/AndroidRuntime( 8552): 	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:470)
E/AndroidRuntime( 8552): 	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:360)
E/AndroidRuntime( 8552): 	at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda-10(MobileScanner.kt:183)
E/AndroidRuntime( 8552): 	at dev.steenbakker.mobile_scanner.MobileScanner.lambda$s9m9vwHudObqldHErksxB98AQmU(Unknown Source:0)
E/AndroidRuntime( 8552): 	at dev.steenbakker.mobile_scanner.-$$Lambda$MobileScanner$s9m9vwHudObqldHErksxB98AQmU.run(Unknown Source:14)
E/AndroidRuntime( 8552): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 8552): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8552): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 8552): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 8552): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8552): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 8552): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/BufferQueueProducer( 8552): [SurfaceTexture-0-8552-0](id:216800000000,api:4,p:396,c:8552) queueBuffer: BufferQueue has been abandoned
I/Process ( 8552): Sending signal. PID: 8552 SIG: 9
Lost connection to device.
Exited (sigterm)
```

**Comment by keltronswgmobile** [comment]
Same issue
