### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by lehoangkhang4869** [juliansteenbakker/mobile_scanner#666]
I see ARN error on my google play console (android 11 sdk 30): 
Exception java.lang.NullPointerException:
  at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda-11$lambda-7 (MobileScanner.java)
  at androidx.camera.core.Preview.lambda$sendSurfaceRequest$1 (Preview.java)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7977)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:603)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:948)
I looked in the project source, but I don't see the file MobileScanner.java, I only see MobileScanner.kt @@

**Comment by rohansohonee1** [comment]
Stacktrace from firebase:
```
Fatal Exception: java.lang.NullPointerException:
       at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda$10$lambda$6(MobileScanner.kt:173)
       at androidx.camera.core.Preview.lambda$sendSurfaceRequestIfReady$1(Preview.java)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Device details:
```
Device
Brand:Samsung
Model:Galaxy Tab A8
Orientation:Portrait
RAM free: 765.36 MB
Disk free: 34.41 GB
Operating System
Version:Android 13
Orientation:Portrait
Rooted:No
Crash
Date:Jun 20, 2023, 4:32:14 PM
```

**Comment by memoriasIT** [comment]
Can reproduce as well. This causes a crash on my app.
To trigger it I just open and close it very quickly.
I can only trigger it on profile or release builds.

<details>
  <summary>A bit more of the logs</summary>
  ```
D/CameraStateRegistry(18782): tryOpenCamera(Camera@3577102[id=0]) [Available Cameras: 1, Already Open: false (Previous state: CLOSED)] --> SUCCESS
D/CameraStateRegistry(18782): Recalculating open cameras:
D/CameraStateRegistry(18782): Camera                                       State                 
D/CameraStateRegistry(18782): -------------------------------------------------------------------
D/CameraStateRegistry(18782): Camera@aed28bd[id=2]                         UNKNOWN               
D/CameraStateRegistry(18782): Camera@a55b275[id=3]                         UNKNOWN               
D/CameraStateRegistry(18782): Camera@3577102[id=0]                         OPENING               
D/CameraStateRegistry(18782): Camera@45e888b[id=1]                         UNKNOWN               
D/CameraStateRegistry(18782): -------------------------------------------------------------------
D/CameraStateRegistry(18782): Open count: 1 (Max allowed: 1)
D/Camera2CameraImpl(18782): {Camera@3577102[id=0]} Opening camera.
D/Camera2CameraImpl(18782): {Camera@3577102[id=0]} Transitioning camera internal state: INITIALIZED --> OPENING
I/ViewRootImpl@afd2038[MainActivity](18782): mWNT: t = android.view.SurfaceControl$Transaction@c1039ff fN = 774 android.view.SyncRtSurfaceTransactionApplier.applyTransaction:94 android.view.SyncRtSurfaceTransactionApplier.lambda$scheduleApply$0$SyncRtSurfaceTransactionApplier:71 android.view.SyncRtSurfaceTransactionApplier$$ExternalSyntheticLambda0.onFrameDraw:4 
I/ViewRootImpl@afd2038[MainActivity](18782): mWNT: merge t to BBQ
D/CameraStateMachine(18782): New public camera state CameraState{type=OPENING, error=null} from OPENING and null
D/CameraStateMachine(18782): Publishing new public camera state CameraState{type=OPENING, error=null}
D/AndroidRuntime(18782): Shutting down VM
D/UseCaseAttachState(18782): All use case: [androidx.camera.core.Preview-305d3f88-0c84-43e5-883a-f71d4863e306110897645, androidx.camera.core.ImageAnalysis-a5a0d4e5-a078-478a-8b44-e16402dce317261242914] for camera: 0
E/AndroidRuntime(18782): FATAL EXCEPTION: main
E/AndroidRuntime(18782): Process: com.greenflux.charge.assist.qa, PID: 18782
E/AndroidRuntime(18782): java.lang.NullPointerException
E/AndroidRuntime(18782): 	at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda$11$lambda$6(MobileScanner.kt:172)
E/AndroidRuntime(18782): 	at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$6xiYqBKE4NOIEBpF_EUVJP0DW6M(Unknown Source:0)
E/AndroidRuntime(18782): 	at dev.steenbakker.mobile_scanner.MobileScanner$$ExternalSyntheticLambda3.onSurfaceRequested(Unknown Source:4)
E/AndroidRuntime(18782): 	at androidx.camera.core.Preview.lambda$sendSurfaceRequest$1(Preview.java:516)
E/AndroidRuntime(18782): 	at androidx.camera.core.Preview$$ExternalSyntheticLambda2.run(Unknown Source:4)
E/AndroidRuntime(18782): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(18782): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(18782): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(18782): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(18782): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/AndroidRuntime(18782): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18782): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(18782): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/CameraManagerGlobal(18782): postSingleUpdate device: camera id 0 status STATUS_NOT_AVAILABLE
I/CameraManagerGlobal(18782): postSingleUpdate device: camera id 0 status STATUS_NOT_AVAILABLE
I/CameraManagerGlobal(18782): postSingleUpdate device: camera id 0 status STATUS_NOT_AVAILABLE
I/CameraManagerGlobal(18782): postSingleUpdate device: camera id 0 status STATUS_NOT_AVAILABLE
I/CameraManagerGlobal(18782): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.greenflux.charge.assist.qa API Level 2
D/Camera2CameraImpl(18782): {Camera@3577102[id=0]} Use case androidx.camera.core.Preview-305d3f88-0c84-43e5-883a-f71d4863e306110897645 ACTIVE
D/UseCaseAttachState(18782): Active and attached use case: [androidx.camera.core.Preview-305d3f88-0c84-43e5-883a-f71d4863e306110897645, androidx.camera.core.ImageAnalysis-a5a0d4e5-a078-478a-8b44-e16402dce317261242914] for camera: 0
D/Camera2CameraImpl(18782): {Camera@3577102[id=0]} Use case androidx.camera.core.ImageAnalysis-a5a0d4e5-a078-478a-8b44-e16402dce317261242914 ACTIVE
D/UseCaseAttachState(18782): Active and attached use case: [androidx.camera.core.Preview-305d3f88-0c84-43e5-883a-f71d4863e306110897645, androidx.camera.core.ImageAnalysis-a5a0d4e5-a078-478a-8b44-e16402dce317261242914] for camera: 0
D/Camera2CameraImpl(18782): {Camera@3577102[id=0]} Issue capture request
D/UseCaseAttachState(18782): Active and attached use case: [androidx.camera.core.Preview-305d3f88-0c84-43e5-883a-f71d4863e306110897645, androidx.camera.core.ImageAnalysis-a5a0d4e5-a078-478a-8b44-e16402dce317261242914] for camera: 0
D/Camera2CameraImpl(18782): {Camera@3577102[id=0]} Use cases [androidx.camera.core.Preview-305d3f88-0c84-43e5-883a-f71d4863e306110897645, androidx.camera.core.ImageAnalysis-a5a0d4e5-a078-478a-8b44-e16402dce317261242914] now DETACHED for camera
D/UseCaseAttachState(18782): All use case: [] for camera: 0
D/Camera2CameraImpl(18782): {Camera@3577102[id=0]} Resetting Capture Session
D/Camera2CameraImpl(18782): {Camera@3577102[id=0]} Releasing session in state OPENING
D/UseCaseAttachState(18782): Active and attached use case: [] for camera: 0
D/UseCaseAttachState(18782): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(18782): {Camera@3577102[id=0]} Closing camera.
```
</details>

<details>
  <summary>Flutter doctor</summary>
  ```
[!] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-x64, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] Network resources
```
</details>

Reproducible with multiple phones, on android.

**Comment by sgsm74** [comment]
Got same issue on Galaxy Tab A7

**Comment by rongliangduan** [comment]
Got same issue on TCL 


RAM (total memory)
- (6,097 MB)
System on Chip (SOC)
Mediatek MT6762V/CA
CPU
4x ARM Cortex-A53 (2000 MHz)
4x ARM Cortex-A53 (1500 MHz)
ABI
arm64-v8a
armeabi-v7a
armeabi
Form factor
Phone
Screen size
720x1640
Screen density (DPI)
320 (xhdpi)
Android version
Android 12 (SDK 31)
OpenGL ES version
3.2
GPU
Imagination Tech PowerVR GE8320 (650 MHz)
Device (per build fingerprint)

**Comment by juliansteenbakker** [comment]
I'm closing this as there is no activity, and newer versions of this plug are already released. If this still happens with the latest version let me know by commenting.
