### ISSUE TITLE
Flash not working in release build

### ISSUE THREAD

**Issue by Fanom2813** [juliansteenbakker/mobile_scanner#718]
Hello !
While in debug mode i can `qrController.toggleTorch()` and it works as expected. , but in release. version it fails with 

`
E/flutter (18172): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method torch on channel dev.steenbakker.mobile_scanner/scanner/method)
E/flutter (18172): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308)
E/flutter (18172): <asynchronous suspension>
E/flutter (18172): #1      MobileScannerController.toggleTorch (package:mobile_scanner/src/mobile_scanner_controller.dart:280)
E/flutter (18172): <asynchronous suspension>
`

**Comment by navaronbracke** [comment]
This works as expected on version 3.5.1. The torch toggles properly in release mode.

**Comment by juliansteenbakker** [comment]
I'm closing this as there is no activity, and newer versions of this plug are already released. If this still happens with the latest version let me know by commenting.
