### ISSUE TITLE
Crash when no cameras are available on Android

### ISSUE THREAD

**Issue by opame-app** [juliansteenbakker/mobile_scanner#762]
Using the mobile_scanner package makes no camera Android devices not compatible. 

Here is the solution: https://developer.android.com/guide/topics/manifest/uses-permission-element

**Comment by opame-app** [comment]
Changing this:
<uses-permission android:name="android.permission.CAMERA" />

for this:
<uses-feature android:name="android.permission.CAMERA" android:required="false"/>

Should fix the issue.

**Comment by opame-app** [comment]
In AndroidManifest.xml changing this:
`<uses-permission android:name="android.permission.CAMERA" />
`
for this:
`<uses-feature android:name="android.permission.CAMERA" android:required="false"/>
`
should fix the issue.

**Comment by navaronbracke** [comment]
Well, apparently the plugin crashes when the device has no camera at all.

For example, if I disable front/back camera for the emulator, I get

```
W/CameraX ( 4715): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4715):      at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:97)
W/CameraX ( 4715):      at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:342)
W/CameraX ( 4715):      at androidx.camera.core.CameraX$$ExternalSyntheticLambda3.run(Unknown Source:10)
W/CameraX ( 4715):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4715):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4715):      at java.lang.Thread.run(Thread.java:764)
W/CameraX ( 4715): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4715):      at androidx.camera.core.CameraSelector.select(CameraSelector.java:82)
W/CameraX ( 4715):      at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:83)
W/CameraX ( 4715):      ... 5 more
D/CameraValidator( 4715): Verifying camera lens facing on generic_x86_arm, lensFacingInteger: null
E/CameraValidator( 4715): Camera LensFacing verification failed, existing cameras: []
W/CameraX ( 4715): Retry init. Start time 93452 current time 94540
W/CameraX ( 4715): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4715):      at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:97)
W/CameraX ( 4715):      at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:342)
W/CameraX ( 4715):      at androidx.camera.core.CameraX$$ExternalSyntheticLambda3.run(Unknown Source:10)
W/CameraX ( 4715):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4715):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4715):      at java.lang.Thread.run(Thread.java:764)
W/CameraX ( 4715): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4715):      at androidx.camera.core.CameraSelector.select(CameraSelector.java:82)
W/CameraX ( 4715):      at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:83)
W/CameraX ( 4715):      ... 5 more
D/CameraValidator( 4715): Verifying camera lens facing on generic_x86_arm, lensFacingInteger: null
E/CameraValidator( 4715): Camera LensFacing verification failed, existing cameras: []
W/CameraX ( 4715): Retry init. Start time 93452 current time 95082
W/CameraX ( 4715): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4715):      at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:97)
W/CameraX ( 4715):      at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:342)
W/CameraX ( 4715):      at androidx.camera.core.CameraX$$ExternalSyntheticLambda3.run(Unknown Source:10)
W/CameraX ( 4715):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4715):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4715):      at java.lang.Thread.run(Thread.java:764)
W/CameraX ( 4715): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4715):      at androidx.camera.core.CameraSelector.select(CameraSelector.java:82)
W/CameraX ( 4715):      at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:83)
W/CameraX ( 4715):      ... 5 more
D/CameraValidator( 4715): Verifying camera lens facing on generic_x86_arm, lensFacingInteger: null
E/CameraValidator( 4715): Camera LensFacing verification failed, existing cameras: []
W/CameraX ( 4715): Retry init. Start time 93452 current time 95629
W/CameraX ( 4715): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 4715):      at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:97)
W/CameraX ( 4715):      at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:342)
W/CameraX ( 4715):      at androidx.camera.core.CameraX$$ExternalSyntheticLambda3.run(Unknown Source:10)
W/CameraX ( 4715):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 4715):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 4715):      at java.lang.Thread.run(Thread.java:764)
W/CameraX ( 4715): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 4715):      at androidx.camera.core.CameraSelector.select(CameraSelector.java:82)
W/CameraX ( 4715):      at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:83)
W/CameraX ( 4715):      ... 5 more
D/CameraValidator( 4715): Verifying camera lens facing on generic_x86_arm, lensFacingInteger: null
E/CameraValidator( 4715): Camera LensFacing verification failed, existing cameras: []
E/CameraX ( 4715): The device might underreport the amount of the cameras. Finish the initialize task since we are already reaching the maximum number of retries.
D/AndroidRuntime( 4715): Shutting down VM
E/AndroidRuntime( 4715): FATAL EXCEPTION: main
E/AndroidRuntime( 4715): Process: dev.steenbakker.mobile_scanner_example, PID: 4715
E/AndroidRuntime( 4715): java.lang.IllegalArgumentException: Provided camera selector unable to resolve a camera for the given use case
E/AndroidRuntime( 4715):        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:476)
E/AndroidRuntime( 4715):        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:363)
E/AndroidRuntime( 4715):        at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda$11(MobileScanner.kt:293)
E/AndroidRuntime( 4715):        at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$QBaqIq_loyYbiAjfq_M2yLd3JMk(Unknown Source:0)
E/AndroidRuntime( 4715):        at dev.steenbakker.mobile_scanner.MobileScanner$$ExternalSyntheticLambda1.run(Unknown Source:18)
E/AndroidRuntime( 4715):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 4715):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4715):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 4715):        at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 4715):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4715):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 4715):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process ( 4715): Sending signal. PID: 4715 SIG: 9
```
