### ISSUE TITLE
[Flutter Web] MissingPluginException :: TypeError: dart.global.jsQR is not a function

### ISSUE THREAD

**Issue by dhruvilp** [juliansteenbakker/mobile_scanner#79]
Another exception was thrown: MissingPluginException(No implementation found for method listen on channel
dev.steenbakker.mobile_scanner/scanner/event)
MobileScannerWeb: AbortError: The play() request was interrupted by a new load request. https://goo.gl/LdLk22

```
TypeError: dart.global.jsQR is not a function
    at mobile_scanner_web_plugin.MobileScannerWebPlugin.new._captureFrame
    (http://localhost:51540/packages/mobile_scanner/mobile_scanner_web_plugin.dart.lib.js:241:32)
    at _captureFrame.next (<anonymous>)
    at runBody (http://localhost:51540/dart_sdk.js:40565:34)
    at Object._async [as async] (http://localhost:51540/dart_sdk.js:40596:7)
    at mobile_scanner_web_plugin.MobileScannerWebPlugin.new.[_captureFrame]
    (http://localhost:51540/packages/mobile_scanner/mobile_scanner_web_plugin.dart.lib.js:235:20)
    at http://localhost:51540/packages/mobile_scanner/mobile_scanner_web_plugin.dart.lib.js:188:32
    at http://localhost:51540/dart_sdk.js:26642:9
```

**Comment by berkutta** [comment]
Check README https://github.com/juliansteenbakker/mobile_scanner#web
