### ISSUE TITLE
CRASH ANDROID API >=30 

### ISSUE THREAD

**Issue by EArminjon** [juliansteenbakker/mobile_scanner#799]
Crash present on master branch 

MobileScanner.kt

```kotlin
val rotation = if (Build.VERSION.SDK_INT >= 30) {
            activity.applicationContext.display!!.rotation
        } else {
```
```bash
java.lang.UnsupportedOperationException: Tried to obtain display from a Context not associated with one. Only visual Contexts (such as Activity or one created with Context#createWindowContext) or ones created with Context#createDisplayContext are associated with displays. Other types of Contexts are typically related to background entities and may return an arbitrary display.
E/AndroidRuntime(22817): 	at android.app.ContextImpl.getDisplay(ContextImpl.java:3025)
E/AndroidRuntime(22817): 	at android.content.ContextWrapper.getDisplay(ContextWrapper.java:1192)
E/AndroidRuntime(22817): 	at dev.steenbakker.mobile_scanner.MobileScanner.getResolution(MobileScanner.kt:185)
E/AndroidRuntime(22817): 	at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda$11(MobileScanner.kt:272)
E/AndroidRuntime(22817): 	at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$QBaqIq_loyYbiAjfq_M2yLd3JMk(Unknown Source:0)
E/AndroidRuntime(22817): 	at dev.steenbakker.mobile_scanner.MobileScanner$$ExternalSyntheticLambda2.run(Unknown Source:18)
E/AndroidRuntime(22817): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(22817): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(22817): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(22817): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(22817): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(22817): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22817): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(22817): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
W/xel.RexelSE.uat(22817): Attempt to remove non-JNI local reference
```

Pixel 7 Android 14.

**Comment by EArminjon** [comment]
Using following code fix the issue  : 

```kotlin
val rotation = if (Build.VERSION.SDK_INT >= 30) {
        activity.display!!.rotation
        } else {
```

Need to check Android compatibility.
