### ISSUE TITLE
Android Camerax crash..

### ISSUE THREAD

**Issue by GeonSeon** [juliansteenbakker/mobile_scanner#837]
using mobile_scanner: ^3.5.1 version in our flutter project..

2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime FATAL EXCEPTION: CameraX-core_camera_0
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime Process: com.caitory.tbm, PID: 15999
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime java.lang.ExceptionInInitializerError
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at androidx.camera.camera2.internal.u.<init>(Unknown Source:135)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at androidx.camera.camera2.internal.Q.<init>(Unknown Source:140)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at androidx.camera.camera2.internal.v.b(Unknown Source:32)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at q.F.b(Unknown Source:47)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at androidx.camera.core.E.b(Unknown Source:108)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at androidx.camera.core.C.run(Unknown Source:10)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.lang.Thread.run(Thread.java:1012)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: q.o.values []
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.lang.Enum.enumValues(Enum.java:272)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.lang.Enum.-$$Nest$smenumValues(Unknown Source:0)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.lang.Enum$1.create(Enum.java:279)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.lang.Enum$1.create(Enum.java:277)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.lang.Enum.getSharedConstants(Enum.java:291)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.lang.Class.getEnumConstantsShared(Class.java:2461)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.util.EnumSet.getUniverse(EnumSet.java:412)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.util.EnumSet.noneOf(EnumSet.java:114)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.util.EnumSet.of(EnumSet.java:288)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at androidx.camera.camera2.internal.u0.<clinit>(Unknown Source:8)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	... 9 more
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime Caused by: java.lang.NoSuchMethodException: q.o.values []
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.lang.Class.getMethod(Class.java:2103)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.lang.Class.getDeclaredMethod(Class.java:2081)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	at java.lang.Enum.enumValues(Enum.java:269)
2023/10/29 01:49:34.436 15999 16242 Error AndroidRuntime 	... 19 more

**Comment by navaronbracke** [comment]
The stacktrace is minified? Could you reproduce this locally and provide a non-minified stacktrace?

This _could_ be related to https://github.com/juliansteenbakker/mobile_scanner/issues/719 but not sure yet (hence why I need access to the non-minified stacktrace)
