### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by palvajk** [juliansteenbakker/mobile_scanner#88]
java.lang.NoClassDefFoundError: androidx.camera.core.impl.utils.futures.ImmediateFuture
        at androidx.camera.core.impl.utils.futures.Futures.immediateFuture(Futures.java:56)
        at androidx.camera.lifecycle.ProcessCameraProvider.<init>(ProcessCameraProvider.java:95)
        at androidx.camera.lifecycle.ProcessCameraProvider.<clinit>(ProcessCameraProvider.java:87)
        at dev.steenbakker.mobile_scanner.MobileScanner.start(MobileScanner.kt:149)
        at dev.steenbakker.mobile_scanner.MobileScanner.onMethodCall(MobileScanner.kt:52)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:320)
        at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by sifat004bk** [comment]
@palvajk how did you fix this?

**Comment by palvajk** [comment]
@sifat004bk 
I has this line in my build.gradle:
implementation "com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava"
I needed to remove it.
