### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Vollinator** [juliansteenbakker/mobile_scanner#92]
Hi,
getting following error after scanning different QR codes using the latest version of the package:

```
D/AndroidRuntime(20736): Shutting down VM
E/AndroidRuntime(20736): FATAL EXCEPTION: main
E/AndroidRuntime(20736): Process: com.example.qrcode_scanner, PID: 20736
E/AndroidRuntime(20736): java.lang.IllegalArgumentException: Unsupported value: '[Ljava.lang.String;@2c3ee7e' of type 'class [Ljava.lang.String;'
E/AndroidRuntime(20736): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:292)
E/AndroidRuntime(20736): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:280)
E/AndroidRuntime(20736): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:272)
3
E/AndroidRuntime(20736): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:280)
E/AndroidRuntime(20736): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:59)
E/AndroidRuntime(20736): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:251)
E/AndroidRuntime(20736): 	at dev.steenbakker.mobile_scanner.MobileScanner.analyzer$lambda-4$lambda-1(MobileScanner.kt:108)
E/AndroidRuntime(20736): 	at dev.steenbakker.mobile_scanner.MobileScanner.lambda$W_K0wEAtbLY7GWki1OWglBLUf6o(Unknown Source:0)
E/AndroidRuntime(20736): 	at dev.steenbakker.mobile_scanner.-$$Lambda$MobileScanner$W_K0wEAtbLY7GWki1OWglBLUf6o.onSuccess(Unknown Source:4)
E/AndroidRuntime(20736): 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
E/AndroidRuntime(20736): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(20736): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(20736): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(20736): 	at android.app.ActivityThread.main(ActivityThread.java:8414)
E/AndroidRuntime(20736): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20736): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
E/AndroidRuntime(20736): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/Process (20736): Sending signal. PID: 20736 SIG: 9
```

**Comment by juliansteenbakker** [comment]
Fixed in #83
