### ISSUE TITLE
the app breaks with VCARD Qrcode

### ISSUE THREAD

**Issue by anCampese** [juliansteenbakker/mobile_scanner#93]
Hi I noticed that the app breaks systematically when I try to scan a VCARD type qrcode. I noticed that this crash occurs when reading any VCARD that contains an ADR key; that is an address. I have attached a sample barcode with which the app breaks.

On crashlytics I have this error:

Fatal Exception: java.lang.IllegalArgumentException: Unsupported value: '[Ljava.lang.String;@a13c65f' of type 'class [Ljava.lang.String;'
       at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:292)
       at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:280)
       at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:272)
       at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:280)
       at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:280)
       at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:280)
       at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:59)
       at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:251)
       at dev.steenbakker.mobile_scanner.MobileScanner.analyzer$lambda-4$lambda-1(MobileScanner.kt:108)
       at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$W_K0wEAtbLY7GWki1OWglBLUf6o()
       at dev.steenbakker.mobile_scanner.MobileScanner$$ExternalSyntheticLambda10.onSuccess(:4)
       at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:263)
       at android.app.ActivityThread.main(ActivityThread.java:8283)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

![WhatsApp Image 2022-04-07 at 12 50 36](https://user-images.githubusercontent.com/88898779/162183021-0fd47896-bd89-417f-bd8c-8f2fb4b20d67.jpeg)

**Comment by juliansteenbakker** [comment]
Fixed in #83
